package com.bms.slim.constant;

/**
 * <p>数据库表常量类。</p>
 */
public interface TableConstant {

	/**
	 * <p>表名。</p>
	 */
	interface Name {
		String SLIM_AGENT_SUPPLY_QUALIFICATION = "SLIM_AGENT_SUPPLY_QUALIFICATION";
		String SLIM_ANIMAL_EPIDEMIC_PREVENTION_CONDITION_CERTIFICATE = "SLIM_ANIMAL_EPIDEMIC_PREVENTION_CONDITION_CERTIFICATE";
		String SLIM_CONTACT = "SLIM_CONTACT";
		String SLIM_DESIGNAT_SLAUGHTER_PERMIT = "SLIM_DESIGNAT_SLAUGHTER_PERMIT";
		String SLIM_ENTITY_SELLER = "SLIM_ENTITY_SELLER";
		String SLIM_FOOD_PRODUCTION_LICENSE = "SLIM_FOOD_PRODUCTION_LICENSE";
		String SLIM_HALAL_FOOD_PRODUCTION_OPERATION_LICENSE = "SLIM_HALAL_FOOD_PRODUCTION_OPERATION_LICENSE";
		String SLIM_ISO_MANAGEMENT_SYSTEM_CERTIFICATION = "SLIM_ISO_MANAGEMENT_SYSTEM_CERTIFICATION";
		String SLIM_MANUFACTURER_SUPPLY_QUALIFICATION = "SLIM_MANUFACTURER_SUPPLY_QUALIFICATION";
		String SLIM_PRODUCER = "SLIM_PRODUCER";
		String SLIM_PRODUCER_FACTORY = "SLIM_PRODUCER_FACTORY";
		String SLIM_PRODUCER_HONOR_CERTIFICATE = "SLIM_PRODUCER_HONOR_CERTIFICATE";
		String SLIM_PRODUCER_LABORATORY = "SLIM_PRODUCER_LABORATORY";
		String SLIM_PRODUCER_STORAGE_CAPACITY = "SLIM_PRODUCER_STORAGE_CAPACITY";
		String SLIM_PRODUCER_TEST_EQUIPMENT = "SLIM_PRODUCER_TEST_EQUIPMENT";
		String SLIM_PRODUCER_WORKSHOP = "SLIM_PRODUCER_WORKSHOP";
		String SLIM_SELLER = "SLIM_SELLER";
		String SLIM_SELLER_BRAND = "SLIM_SELLER_BRAND";
		String SLIM_SELLER_BUSINESS_QUALIFICATION = "SLIM_SELLER_BUSINESS_QUALIFICATION";
		String SLIM_SELLER_BUSINESS_TEAM = "SLIM_SELLER_BUSINESS_TEAM";
		String SLIM_SELLER_CONTRACT_PERMISSION = "SLIM_SELLER_CONTRACT_PERMISSION";
		String SLIM_SELLER_MANAGEMENT_TEAM = "SLIM_SELLER_MANAGEMENT_TEAM";
		String SLIM_SELLER_PRODUCER = "SLIM_SELLER_PRODUCER";
		String SLIM_SH_BJ_TJ_REGISTRATION = "SLIM_SH_BJ_TJ_REGISTRATION";
		String SLIM_SELLER_ROLE = "SLIM_SELLER_ROLE";
    }
	
}
