package com.bms.slpd.constant;

/**
 * <p>数据库表常量类。</p>
 */
public interface TableConstant {

	/**
	 * <p>表名。</p>
	 */
	interface Name {
		String SLPD_BRAND = "SLPD_BRAND";
        String SLPD_BRAND_OWNER = "SLPD_BRAND_OWNER";
        String SLPD_BRAND_OWNER_RELATION = "SLPD_BRAND_OWNER_RELATION";

		String SLPD_CLASSES = "SLPD_CLASSES";
        String SLPD_MACHINING = "SLPD_MACHINING";
        String SLPD_BREED = "SLPD_BREED";
        String SLPD_ITEM = "SLPD_ITEM";

        String SLPD_BRAND_ITEM = "SLPD_BRAND_ITEM";
        String SLPD_ITEM_PROPERTY = "SLPD_ITEM_PROPERTY";
        String SLPD_PRODUCT = "SLPD_PRODUCT";

        String SLPD_PRODUCER_PRODUCT = "SLPD_PRODUCER_PRODUCT";
        String SLPD_MANUFACTURER_PRODUCT = "SLPD_PRODUCER_PRODUCT";
		String SLPD_COMMODITY = "SLPD_COMMODITY";
        String SLPD_SELLER_COMMODITY = "SLPD_SELLER_COMMODITY";

        String SLPD_BREED_STD_RELATION = "SLPD_BREED_STD_RELATION";
        String SLPD_DISCUSS_STD = "SLPD_DISCUSS_STD";
		String SLPD_DIF_DISCUSS_STD = "SLPD_DIF_DISCUSS_STD";

		String SLPD_DIF_FED_STD = "SLPD_DIF_FED_STD";
		String SLPD_DIF_GNQ_STD = "SLPD_DIF_GNQ_STD";
        String SLPD_DIF_MCT_STD = "SLPD_DIF_MCT_STD";
        String SLPD_DIF_ORG_STD = "SLPD_DIF_ORG_STD";
        String SLPD_DIF_PKG_STD = "SLPD_DIF_PKG_STD";
        String SLPD_DIF_SFT_STD = "SLPD_DIF_SFT_STD";
        String SLPD_DIF_TNC_STD = "SLPD_DIF_TNC_STD";
        String SLPD_DIF_TSP_STD = "SLPD_DIF_TSP_STD";

        String SLPD_FED_STD = "SLPD_FED_STD";
        String SLPD_GNQ_STD = "SLPD_GNQ_STD";
        String SLPD_MCT_STD = "SLPD_MCT_STD";
        String SLPD_ORG_STD = "SLPD_ORG_STD";
        String SLPD_PKG_STD = "SLPD_PKG_STD";
        String SLPD_SFT_STD = "SLPD_SFT_STD";
        String SLPD_TNC_STD = "SLPD_TNC_STD";
        String SLPD_TSP_STD = "SLPD_TSP_STD";

        String SLPD_FED_STD_TYPE = "SLPD_FED_STD_TYPE";
        String SLPD_GNQ_STD_TYPE = "SLPD_GNQ_STD_TYPE";
        String SLPD_MCT_STD_TYPE = "SLPD_MCT_STD_TYPE";
        String SLPD_ORG_STD_TYPE = "SLPD_ORG_STD_TYPE";
        String SLPD_PKG_STD_TYPE = "SLPD_PKG_STD_TYPE";
        String SLPD_SFT_STD_TYPE = "SLPD_SFT_STD_TYPE";
        String SLPD_TNC_STD_TYPE = "SLPD_TNC_STD_TYPE";
        String SLPD_TSP_STD_TYPE = "SLPD_TSP_STD_TYPE";

        String SLPD_BRAND_POOL = "SLPD_BRAND_POOL";
		String SLPD_MANUFACTURE_GRADE_EVALUATE = "SLPD_MANUFACTURE_GRADE_EVALUATE";
        String SLPD_ITEM_BRAND_PRODUCER_BATCH = "SLPD_ITEM_BRAND_PRODUCER_BATCH";
        String SLPD_ITEM_BRAND_PRODUCER_BATCH_SALE = "SLPD_ITEM_BRAND_PRODUCER_BATCH_SALE";
		String SLPD_PRODUCER_SELLER_ONLINE = "SLPD_PRODUCER_SELLER_ONLINE";
        String SLPD_PROVINCE_SELLER_POOL_PRODUCER_SELLER = "SLPD_PROVINCE_SELLER_POOL_PRODUCER_SELLER";
        String SLPD_PROVINCE_SELLER_REGISTER = "SLPD_PROVINCE_SELLER_REGISTER";
        String SLPD_PROVINCE_SELLER_STANDARD_POOL = "SLPD_PROVINCE_SELLER_STANDARD_POOL";

        String SLPD_LOGISTICS_AREA_PRODUCT = "SLPD_LOGISTICS_AREA_PRODUCT";

        String SLPD_AGENT_SUPPLY_PRODUCT = "SLPD_AGENT_SUPPLY_PRODUCT";
    }
	
}
